// <auto-generated />
using System;
using Learner_Management_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Learner_Management_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260416180823_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("Learner_Management_System.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("QualificationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AdminId");

                    b.HasIndex("QualificationId");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("Learner_Management_System.Models.AdminUpload", b =>
                {
                    b.Property<int>("UploadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdminId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QualificationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UploadCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UploadedByUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UploadId");

                    b.HasIndex("AdminId");

                    b.HasIndex("QualificationId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("AdminUploads", (string)null);
                });

            modelBuilder.Entity("Learner_Management_System.Models.Assessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssessmentBankId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssessmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssessmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PassingScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("QualificationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeightPercentage")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssessmentId");

                    b.HasIndex("AssessmentBankId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("QualificationId");

                    b.HasIndex("Status");

                    b.ToTable("Assessments", (string)null);
                });

            modelBuilder.Entity("Learner_Management_System.Models.AssessmentBank", b =>
                {
                    b.Property<int>("AssessmentBankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssessorDeveloperId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("QualificationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("AssessmentBankId");

                    b.HasIndex("AssessorDeveloperId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("QualificationId");

                    b.ToTable("AssessmentBanks", (string)null);
                });

            modelBuilder.Entity("Learner_Management_System.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClassSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LearnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("AttendanceId");

                    b.HasIndex("ClassSessionId");

                    b.HasIndex("LearnerId");

                    b.ToTable("Attendances", (string)null);
                });

            modelBuilder.Entity("Learner_Management_System.Models.ClassSession", b =>
                {
                    b.Property<int>("ClassSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualificationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VenueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClassSessionId");

                    b.HasIndex("QualificationId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("VenueId");

                    b.ToTable("ClassSessions", (string)null);
                });

            modelBuilder.Entity("Learner_Management_System.Models.Cost", b =>
                {
                    b.Property<int>("CostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CostType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("CostId");

                    b.ToTable("Costs", (string)null);
                });

            modelBuilder.Entity("Learner_Management_System.Models.DocumentWorkflow", b =>
                {
                    b.Property<int>("WorkflowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AdminUploadId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssessmentBankId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssessmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Feedback")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PreviousStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RandomizedPaperId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkflowId");

                    b.HasIndex("ActionByUserId");

                    b.HasIndex("AdminUploadId");

                    b.HasIndex("AssessmentBankId");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("RandomizedPaperId");

                    b.HasIndex("Status");

                    b.ToTable("DocumentWorkflows", (string)null);
                });

            modelBuilder.Entity("Learner_Management_System.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FinalGrade")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("LearnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualificationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("LearnerId");

                    b.HasIndex("QualificationId");

                    b.HasIndex("Status");

                    b.ToTable("Enrollments", (string)null);
                });

            modelBuilder.Entity("Learner_Management_System.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClassSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FeedbackDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedbackText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("LearnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FeedbackId");

                    b.HasIndex("ClassSessionId");

                    b.HasIndex("LearnerId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Feedbacks", (string)null);
                });

            modelBuilder.Entity("Learner_Management_System.Models.Grades", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssessmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GradeDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LearnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LetterGrade")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("GradeId");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("LearnerId");

                    b.ToTable("Grades", (string)null);
                });

            modelBuilder.Entity("Learner_Management_System.Models.LearnerUpload", b =>
                {
                    b.Property<int>("UploadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssessmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LearnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewComments")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("TEXT");

                    b.HasKey("UploadId");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("LearnerId");

                    b.ToTable("LearnerUploads", (string)null);
                });

            modelBuilder.Entity("Learner_Management_System.Models.Learners", b =>
                {
                    b.Property<int>("LearnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("LearnerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Learners", (string)null);
                });

            modelBuilder.Entity("Learner_Management_System.Models.Qualification", b =>
                {
                    b.Property<int>("QualificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationInHours")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("QualificationCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("QualificationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("QualificationId");

                    b.HasIndex("QualificationCode");

                    b.ToTable("Qualifications", (string)null);
                });

            modelBuilder.Entity("Learner_Management_System.Models.Qualification_cost", b =>
                {
                    b.Property<int>("QualificationCostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualificationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("QualificationCostId");

                    b.HasIndex("CostId");

                    b.HasIndex("QualificationId");

                    b.ToTable("QualificationCosts", (string)null);
                });

            modelBuilder.Entity("Learner_Management_System.Models.RandomizedPaper", b =>
                {
                    b.Property<int>("RandomizedPaperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssessmentBankId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaperName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaperVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("QualificationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuestionPoolSize")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuestionsPerPaper")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RandomizationSeed")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UploadedByUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RandomizedPaperId");

                    b.HasIndex("AssessmentBankId");

                    b.HasIndex("QualificationId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("RandomizedPapers", (string)null);
                });

            modelBuilder.Entity("Learner_Management_System.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialization")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("TeacherId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Teachers", (string)null);
                });

            modelBuilder.Entity("Learner_Management_System.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("QualificationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Specialization")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("QualificationId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Learner_Management_System.Models.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Facilities")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("VenueId");

                    b.ToTable("Venues", (string)null);
                });

            modelBuilder.Entity("Learner_Management_System.Models.Admin", b =>
                {
                    b.HasOne("Learner_Management_System.Models.Qualification", "Qualification")
                        .WithMany("Admins")
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Qualification");
                });

            modelBuilder.Entity("Learner_Management_System.Models.AdminUpload", b =>
                {
                    b.HasOne("Learner_Management_System.Models.Admin", "Admin")
                        .WithMany("Uploads")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learner_Management_System.Models.Qualification", "Qualification")
                        .WithMany("AdminUploads")
                        .HasForeignKey("QualificationId");

                    b.HasOne("Learner_Management_System.Models.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId");

                    b.Navigation("Admin");

                    b.Navigation("Qualification");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Learner_Management_System.Models.Assessment", b =>
                {
                    b.HasOne("Learner_Management_System.Models.AssessmentBank", "AssessmentBank")
                        .WithMany("Assessments")
                        .HasForeignKey("AssessmentBankId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Learner_Management_System.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("Learner_Management_System.Models.Qualification", "Qualification")
                        .WithMany("Assessments")
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssessmentBank");

                    b.Navigation("CreatedBy");

                    b.Navigation("Qualification");
                });

            modelBuilder.Entity("Learner_Management_System.Models.AssessmentBank", b =>
                {
                    b.HasOne("Learner_Management_System.Models.User", "AssessorDeveloper")
                        .WithMany()
                        .HasForeignKey("AssessorDeveloperId");

                    b.HasOne("Learner_Management_System.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("Learner_Management_System.Models.Qualification", "Qualification")
                        .WithMany("AssessmentBanks")
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessorDeveloper");

                    b.Navigation("CreatedBy");

                    b.Navigation("Qualification");
                });

            modelBuilder.Entity("Learner_Management_System.Models.Attendance", b =>
                {
                    b.HasOne("Learner_Management_System.Models.ClassSession", "ClassSession")
                        .WithMany("Attendances")
                        .HasForeignKey("ClassSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learner_Management_System.Models.Learners", "Learner")
                        .WithMany("Attendances")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassSession");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("Learner_Management_System.Models.ClassSession", b =>
                {
                    b.HasOne("Learner_Management_System.Models.Qualification", "Qualification")
                        .WithMany("ClassSessions")
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Learner_Management_System.Models.Teacher", "Teacher")
                        .WithMany("ClassSessions")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Learner_Management_System.Models.Venue", "Venue")
                        .WithMany("ClassSessions")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Qualification");

                    b.Navigation("Teacher");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Learner_Management_System.Models.DocumentWorkflow", b =>
                {
                    b.HasOne("Learner_Management_System.Models.User", "ActionBy")
                        .WithMany("WorkflowActions")
                        .HasForeignKey("ActionByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Learner_Management_System.Models.AdminUpload", "AdminUpload")
                        .WithMany("WorkflowHistory")
                        .HasForeignKey("AdminUploadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Learner_Management_System.Models.AssessmentBank", "AssessmentBank")
                        .WithMany("WorkflowHistory")
                        .HasForeignKey("AssessmentBankId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Learner_Management_System.Models.Assessment", "Assessment")
                        .WithMany("WorkflowHistory")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Learner_Management_System.Models.RandomizedPaper", "RandomizedPaper")
                        .WithMany("WorkflowHistory")
                        .HasForeignKey("RandomizedPaperId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActionBy");

                    b.Navigation("AdminUpload");

                    b.Navigation("Assessment");

                    b.Navigation("AssessmentBank");

                    b.Navigation("RandomizedPaper");
                });

            modelBuilder.Entity("Learner_Management_System.Models.Enrollment", b =>
                {
                    b.HasOne("Learner_Management_System.Models.Learners", "Learner")
                        .WithMany("Enrollments")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Learner_Management_System.Models.Qualification", "Qualification")
                        .WithMany("Enrollments")
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Learner");

                    b.Navigation("Qualification");
                });

            modelBuilder.Entity("Learner_Management_System.Models.Feedback", b =>
                {
                    b.HasOne("Learner_Management_System.Models.ClassSession", "ClassSession")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ClassSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Learner_Management_System.Models.Learners", "Learner")
                        .WithMany("Feedbacks")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Learner_Management_System.Models.Teacher", "Teacher")
                        .WithMany("Feedbacks")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClassSession");

                    b.Navigation("Learner");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Learner_Management_System.Models.Grades", b =>
                {
                    b.HasOne("Learner_Management_System.Models.Assessment", "Assessment")
                        .WithMany("Grades")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Learner_Management_System.Models.Learners", "Learner")
                        .WithMany("Grades")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("Learner_Management_System.Models.LearnerUpload", b =>
                {
                    b.HasOne("Learner_Management_System.Models.Assessment", "Assessment")
                        .WithMany("Uploads")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Learner_Management_System.Models.Learners", "Learner")
                        .WithMany("Uploads")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("Learner_Management_System.Models.Qualification_cost", b =>
                {
                    b.HasOne("Learner_Management_System.Models.Cost", "Cost")
                        .WithMany("QualificationCosts")
                        .HasForeignKey("CostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Learner_Management_System.Models.Qualification", "Qualification")
                        .WithMany("QualificationCosts")
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cost");

                    b.Navigation("Qualification");
                });

            modelBuilder.Entity("Learner_Management_System.Models.RandomizedPaper", b =>
                {
                    b.HasOne("Learner_Management_System.Models.AssessmentBank", "AssessmentBank")
                        .WithMany("RandomizedPapers")
                        .HasForeignKey("AssessmentBankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Learner_Management_System.Models.Qualification", "Qualification")
                        .WithMany("RandomizedPapers")
                        .HasForeignKey("QualificationId");

                    b.HasOne("Learner_Management_System.Models.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId");

                    b.Navigation("AssessmentBank");

                    b.Navigation("Qualification");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Learner_Management_System.Models.User", b =>
                {
                    b.HasOne("Learner_Management_System.Models.Qualification", "Qualification")
                        .WithMany("Users")
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Qualification");
                });

            modelBuilder.Entity("Learner_Management_System.Models.Admin", b =>
                {
                    b.Navigation("Uploads");
                });

            modelBuilder.Entity("Learner_Management_System.Models.AdminUpload", b =>
                {
                    b.Navigation("WorkflowHistory");
                });

            modelBuilder.Entity("Learner_Management_System.Models.Assessment", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("Uploads");

                    b.Navigation("WorkflowHistory");
                });

            modelBuilder.Entity("Learner_Management_System.Models.AssessmentBank", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("RandomizedPapers");

                    b.Navigation("WorkflowHistory");
                });

            modelBuilder.Entity("Learner_Management_System.Models.ClassSession", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("Learner_Management_System.Models.Cost", b =>
                {
                    b.Navigation("QualificationCosts");
                });

            modelBuilder.Entity("Learner_Management_System.Models.Learners", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Enrollments");

                    b.Navigation("Feedbacks");

                    b.Navigation("Grades");

                    b.Navigation("Uploads");
                });

            modelBuilder.Entity("Learner_Management_System.Models.Qualification", b =>
                {
                    b.Navigation("AdminUploads");

                    b.Navigation("Admins");

                    b.Navigation("AssessmentBanks");

                    b.Navigation("Assessments");

                    b.Navigation("ClassSessions");

                    b.Navigation("Enrollments");

                    b.Navigation("QualificationCosts");

                    b.Navigation("RandomizedPapers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Learner_Management_System.Models.RandomizedPaper", b =>
                {
                    b.Navigation("WorkflowHistory");
                });

            modelBuilder.Entity("Learner_Management_System.Models.Teacher", b =>
                {
                    b.Navigation("ClassSessions");

                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("Learner_Management_System.Models.User", b =>
                {
                    b.Navigation("WorkflowActions");
                });

            modelBuilder.Entity("Learner_Management_System.Models.Venue", b =>
                {
                    b.Navigation("ClassSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
